---
- hosts: all
  remote_user: ubuntu
  become: true
  tasks:
    - include: ../automoate-conf-ansible/installDocker/tasks/main.yml
    - include: ../automoate-conf-ansible/deploy-app-gozem/tasks/main.yml
    - include: ../automoate-conf-ansible/gitlabRunner/tasks/main.yml