- name: curl binaire to install docker-compose
  get_url:
    url:  https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64
    dest: /usr/local/bin/gitlab-runner
    mode: 'a+x'

- name: add gitlab-runner to sudo group
  user:
    name: "gitlab-runner"
    groups: "sudo"
    comment: "Gitlab runner user"
    shell: /bin/bash
    home: /home/gitlab-runner
    append: yes

- name: install gitlab-runner
  shell: gitlab-runner install --user=gitlab-runner --working-directory=/home/gitlab-runner

- name:  start service gitlab_runner
  service:
    name: "gitlab-runner"
    state: started
    enabled: yes